apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops-operator
  annotations:
    openshift.io/display-name: "OpenShift GitOps Operator"
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    openshift.io/cluster-monitoring: 'true'
